/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the test suite instance being used. In the 
 * SmarTest Work Center, you can navigate to the generating test method 
 * source by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over the following:
 * 
 *   The test method location which resulted in the creation of this file:
 *   SPI/awg.java:30
 * 
 *      The name of the test suite is: Main.Continuity_Leakage.AWG
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
spec Spec_1
{
    setup dcVI OFF_PS1600
    {
        connect = true;
        disconnect = false;
        level.irange = 50.00 mA;
        level.vrange = 3 V;
    
        action sourceWaveform _action_1
        {
            forceType = voltage;
            waveform = _wf_1;
            iclamp = 20.00 mA;
        }
    }
    
    waveform ramp _wf_1
    {
        startValue = 2.9;
        stopValue = 0;
        samples = 1000;
        sampleRate = 1 kHz;
    }
    action _action_1;
}
