/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the test suite instance being used. In the 
 * SmarTest Work Center, you can navigate to the generating test method 
 * source by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over the following:
 * 
 *   The test method location which resulted in the creation of this file:
 *   SPI/UVLO.java:26
 * 
 *      The name of the test suite is: Main.Continuity_Leakage.UVLO
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
spec Spec_1
{
    setup dcVI ITRIP_PS1600
    {
        connect = true;
    
        action vforce vForce_ITRIP_0V
        {
            vrange = 3 V;
            forceValue = 0 V;
            iclamp = 40.00 mA;
            irange = 40.00 mA;
        }
    }
    
    setup dcVI ISEN_PS1600
    {
        connect = true;
    
        action vforce vForce_ISEN_0V
        {
            vrange = 3 V;
            forceValue = 0 V;
            iclamp = 40.00 mA;
            irange = 40.00 mA;
        }
    }
    
    setup dcVI VIN1
    {
        connect = true;
    
        action vforce vForce_VIN1_0V
        {
            vrange = 5 V;
            forceValue = 0 V;
            iclamp = 40.00 mA;
            irange = 50.00 mA;
        }
    
        action vforce vForce_VIN1_5V
        {
            vrange = 5 V;
            forceValue = 5 V;
            iclamp = 40.00 mA;
            irange = 50.00 mA;
        }
    }
    
    setup dcVI EN0_PS1600+FCB_PS1600
    {
        action vforce vForce_EN0_FCB_0V
        {
            vrange = 2 V;
            forceValue = 0 V;
            iclamp = 40.00 mA;
            irange = 40.00 mA;
        }
    
        action vforce vForce_EN0_FCB_3V
        {
            vrange = 4 V;
            forceValue = 3 V;
            iclamp = 40.00 mA;
            irange = 40.00 mA;
        }
    }
    
    setup dcVI VDD
    {
        connect = true;
    
        action vforce vForce_VDD_0V
        {
            vrange = 10 V;
            forceValue = 0 V;
            iclamp = 40.00 mA;
            irange = 50.00 mA;
        }
    
        action sourceWaveform _action_1
        {
            forceType = voltage;
            waveform = _wf_1;
            iclamp = 200.0 mA;
        }
    
        action sourceWaveform _action_2
        {
            forceType = voltage;
            waveform = _wf_2;
            iclamp = 200.0 mA;
        }
    }
    
    setup dcVI OFF_PS1600
    {
        disconnect = true;
    
        action disconnect _action_5
        {
        }
    }
    
    setup dcVI OFF_PS1600
    {
        disconnect = true;
    
        action iforce _action_3
        {
            forceValue = 0 A;
            vclampLow = -1 V;
            vclampHigh = 1 V;
        }
    
        action measureWaveform Off_PPMU_MEAS_ACTION
        {
            highAccuracy = true;
            sampleRate = 10 Hz;
            samples = 128;
            measType = voltage;
        }
    }
    
    setup dcVI VOUT4
    {
        connect = true;
    
        action iforce vForce_VOUT4_0A
        {
            irange = 50.00 mA;
            forceValue = 0 A;
            vclampLow = -1 V;
            vclampHigh = 1 V;
        }
    
        action iforce _action_4
        {
            forceValue = 0 A;
            vclampLow = -1 V;
            vclampHigh = 1 V;
        }
    
        action measureWaveform VOUT4_MEAS_ACTION
        {
            highAccuracy = true;
            sampleRate = 10 Hz;
            samples = 128;
            measType = voltage;
        }
    }
    
    setup utility GND_K9_TGND + VIN6_K28_DIODE_VOUT1
    {
        value = 1;
    }
    
    setup utility SS_K23_CAP
    {
        value = 1;
    }
    action vForce_ITRIP_0V;
    action vForce_ISEN_0V;
    action vForce_EN0_FCB_0V;
    action vForce_VIN1_0V;
    action vForce_VDD_0V;
    action vForce_VIN1_5V;
    action vForce_VOUT4_0A;
    action vForce_EN0_FCB_3V;
    
    waveform ramp _wf_1
    {
        startValue = 0;
        stopValue = 2.9;
        samples = 500;
        sampleRate = 1.5 kHz;
    }
    action _action_1;
    
    waveform ramp _wf_2
    {
        startValue = 2.9;
        stopValue = 0;
        samples = 500;
        sampleRate = 1.5 kHz;
    }
    action _action_2;
    action _action_3;
    action Off_PPMU_MEAS_ACTION;
    action _action_4;
    action VOUT4_MEAS_ACTION;
    action _action_5;
}
