/* ---------------------------------------------------------------------------*
 * 
 * This file was automatically generated by the SmarTest Device Setup API.
 * 
 * The contents of this file are generated by a combination of the 
 * test method code as well as the test suite instance being used. In the 
 * SmarTest Work Center, you can navigate to the generating test method 
 * source by holding down the CTRL+ALT+R keys when your cursor is positioned 
 * over the following:
 * 
 *   The test method location which resulted in the creation of this file:
 *   SPI/dcVI_two_step_measure_1.java:29
 * 
 *      The name of the test suite is: Main.Continuity_Leakage.dcVI_two_step_measure
 * 
 * This file is not intended to be modified. Do not make changes
 * to this file as your changes may be overwritten when the
 * generating code is executed again!
 *
 * ---------------------------------------------------------------------------*/
spec Spec_1
{
    setup dcVI SS_PS1600
    {
        level.vrange = 2 V;
        level.irange = 40.00 mA;
    
        action iforce _action_1
        {
            forceValue = 33.333000 mA;
            vclampLow = 0 V;
            vclampHigh = 5 V;
        }
    
        action vmeas _action_2
        {
            waitTime = 0 s;
            averages = 100;
        }
    }
    action _action_1;
    action _action_2;
}
